graph LR

D1(Cast Distri in Industry) <--> D
D2(Sexual Assualt Compensation) <--> D
D3(a11yscore) <--> D
D4(Scholarships) <--> D

D(Research Wing: <head unknown>?) <--> A

X1[Unknown 1] & X2[Unknown 2] <--> E
E(Placements: <head unknown>?) <--> A

A[(Leadership)] <--> B(Tech...Team?)
A <--> C(Content & PR)
A <--> F(Mentorship)

F <--> Collaborations

C <--> B1(Design)
C <--> B2(Writing)
C <--> B6(Podcasts)

F <--> F1(Software Engg)
F <--> F2(Data Analysis)
F <--> F3(Collaboration)

style F fill:#2af,color:#000
style C fill:#2af,color:#000
style B fill:#2af,color:#000
style E fill:#2af,color:#000
style D fill:#2af,color:#000